[package]
name = "health"
version = "0.1.0"
edition = "2024"

[dependencies]
# local
app-core={workspace = true}
# dependency
axum ={ workspace = true}
serde_json ={ workspace = true}
sqlx ={ workspace = true}